name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  pull_request_target:
    types:
      - synchronize
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [ chromium, firefox, webkit ]
    container:
      image: mcr.microsoft.com/playwright/java:v1.39.0-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress
      - name: Run tests
        run:  mvn test -D exec.args="test --browser ${{ matrix.browser }}"

      - name: Upload Log File
        if: always()
        uses: actions/upload-artifact@v3
        with:
            name: Log ${{ matrix.browser }}
            path: log/*

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: AllureReport ${{ matrix.browser }}
          path: target/allure-results/*

      - name: Upload Downloaded File
        if: always()
        uses: actions/upload-artifact@v3
        with:
            name: Download ${{ matrix.browser }}
            path: Download/*