name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run the tests on'
        required: false
        default: 'chromium'
        type: choice
        options:
            - chromium
            - firefox
            - webkit
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  pull_request_target:
    types:
      - synchronize
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    if:  ${{ inputs.browser }}
    strategy:
      matrix:
        browser: [ chromium, firefox, webkit ]
    container:
      image: mcr.microsoft.com/playwright/java:v1.39.0-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress
      - name: Run tests
        run: |
            if [ -z "${{ github.event.inputs.browser }}" ]; then
              mvn test -D exec.args="test --browser ${{ matrix.browser }}"
            else
              mvn test -D exec.args="test --browser ${{ github.event.inputs.browser }}"
            fi
          
          env:
            BROWSER: ${{ github.event.inputs.browser }}
          if: github.event_name == 'workflow_dispatch' && github.event.inputs.browser != ''

      - name: Run tests on multiple browsers
        run: mvn test -D exec.args="test --browser ${{ matrix.browser }}"
        if: github.event_name != 'workflow_dispatch' || (github.event_name == 'workflow_dispatch' && github.event.inputs.browser == '')

      - name: Upload Log File
        if: always()
        uses: actions/upload-artifact@v3
        with:
            name: Log ${{ matrix.browser }}
            path: log/*

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: AllureReport ${{ matrix.browser }}
          path: target/allure-results/*

      - name: Upload Downloaded File
        if: always()
        uses: actions/upload-artifact@v3
        with:
            name: Download ${{ matrix.browser }}
            path: Download/*