name: PlaywrightTests
on: push
jobs:
  playwright:
    name: 'PlaywrightTests'
    runs-on: windows-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.39.0-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Build & Install
        run: mvnw.cmd install -DskipTests=true --no-transfer-progress

      - name: Install Playwright
        run: mvnw.cmd exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"

      - name: Run tests
        run: mvnw.cmd test