name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run the tests on'
        required: false
        default: ''
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  pull_request_target:
    types:
      - synchronize
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.39.0-jammy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build & Install
        run: mvn -B install -D skipTests --no-transfer-progress

      - name: Run tests
        run: |
          if [ -z "${{ github.event.inputs.browser }}" ]; then
            mvn test -D exec.args="test --browser chromium"
            mvn test -D exec.args="test --browser firefox"
            mvn test -D exec.args="test --browser webkit"
          else
            mvn test -D exec.args="test --browser ${{ github.event.inputs.browser }}"
          fi
        shell: bash

      - name: Upload Log File
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Log ${{ github.event.inputs.browser || matrix.browser }}
          path: log/*

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: AllureReport ${{ github.event.inputs.browser || matrix.browser }}
          path: target/allure-results/*

      - name: Upload Downloaded File
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Download ${{ github.event.inputs.browser || matrix.browser }}
          path: Download/*